using AutoRest.Core.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AutoRest.Java.Azure.Fluent.Model
{
    /// <summary>
    /// The impl-metadata model that can generate a groupable model implementation.
    /// </summary>
    public class GroupableFluentModelImpl
    {

        public GroupableFluentModelImpl(GroupableFluentModel mInterface)
        {
            this.Interface = mInterface;
        }

        /// <summary>
        /// Reference to the interface-metadata model rpresenting the groupable model 
        /// interface that is implemented by the model implementation generated by this
        /// impl-metadata model.
        /// </summary>
        public GroupableFluentModel Interface
        {
            get; private set;
        }

        /// <summary>
        /// Name of the Java class this impl-metadata model generates.
        /// </summary>
        public string JvaClassName
        {
            get
            {
                return $"{this.Interface.JavaInterfaceName}Impl";
            }
        }

        /// <summary>
        /// The Java type of the inner model.
        /// </summary>
        public string InnerModelTypeName
        {
            get
            {
                return this.Interface.InnerModel.Name;
            }
        }

        /// <summary>
        /// The Java type of the inner method group (operation group).
        /// </summary>
        public string InnerMethodGroupTypeName
        {
            get
            {
                return this.Interface.FluentMethodGroup.InnerMethodGroup.MethodGroupImplType;
            }
        }

        public string CtrImplementation
        {
            get
            {
                StringBuilder methodBuilder = new StringBuilder();
                methodBuilder.AppendLine($"{JvaClassName}(String name, {InnerModelTypeName} inner, {this.Interface.FluentMethodGroup.ManagerTypeName} manager) {{");
                methodBuilder.AppendLine($"    super(name, inner, manager);");
                foreach(string initvariable in InitCreateAndUpdateVariables)
                {
                    methodBuilder.AppendLine($"    {initvariable}");
                }
                methodBuilder.AppendLine($"}}");
                return methodBuilder.ToString();
            }
        }

        /// <summary>
        /// Checks 'updateResourceAsync' method needs to be overriden.
        /// </summary>
        public bool NeedUpdateResourceAsyncMethod
        {
            get
            {
                return this.Interface.SupportsUpdating && !this.IsCreateUpdateInnerMethodSame;
            }
        }

        /// <summary>
        /// Return a string collection with 0 to 2 entries, each one represents declaration of variables
        /// used as parameter to create, update or createOrUpdate inner method calls.
        /// </summary>
        public IEnumerable<string> DeclareCreateAndUpdateVariables
        {
            get
            {
                string n1 = Interface.InnerModel.Name;
                string n2 = Interface.CreatePayloadInnerModel.Name;
                string n3 = Interface.UpdatePayloadInnerModel.Name;

                if (n1.Equals(n2) && n1.Equals(n3)) // inner type, create param type & update param type are same
                {
                    yield break;
                }
                if (n1.Equals(n2))  // inner type & create param type are same
                {
                    yield return $"private {Interface.UpdatePayloadInnerModel.Name} updateParameter;";
                }
                else if (n1.Equals(n3)) // inner type & update param type are same
                {
                    yield return $"private {Interface.CreatePayloadInnerModel.Name} createParameter;";
                }
                else if (n2.Equals(n3))  // create type & update param type are same
                {
                    yield return $"private {Interface.CreatePayloadInnerModel.Name} createOrUpdateParameter;";
                }
                else
                {
                    yield return $"private {Interface.UpdatePayloadInnerModel.Name} updateParameter;";
                    yield return $"private {Interface.CreatePayloadInnerModel.Name} createParameter;";
                }
            }
        }

        /// <summary>
        /// Return a string collection with 0 to 2 entries, each one represents initialization of variables
        /// used for create, update or createOrUpdate inner method calls.
        /// </summary>
        public IEnumerable<string> InitCreateAndUpdateVariables
        {
            get
            {
                string n1 = Interface.InnerModel.Name;
                string n2 = Interface.CreatePayloadInnerModel.Name;
                string n3 = Interface.UpdatePayloadInnerModel.Name;

                if (n1.Equals(n2) && n1.Equals(n3)) // inner type, create param type & update param type are same
                {
                    yield break;
                }
                if (n1.Equals(n2))  // inner type & create param type are same
                {
                    yield return $"this.updateParameter = new {Interface.UpdatePayloadInnerModel.Name}();";
                }
                else if (n1.Equals(n3)) // inner type & update param type are same
                {
                    yield return $"this.createParameter = new {Interface.CreatePayloadInnerModel.Name}();";
                }
                else if (n2.Equals(n3))  // create type & update param type are same
                {
                    yield return $"this.createOrUpdateParameter = new {Interface.CreatePayloadInnerModel.Name}();";
                }
                else
                {
                    yield return $"this.updateParameter = new {Interface.UpdatePayloadInnerModel.Name}();";
                    yield return $"this.createParameter = new {Interface.CreatePayloadInnerModel.Name}();";
                }
            }
        }

        /// <summary>
        /// Return Java variable name (or accessor) used as the value of resource create inner call.
        /// </summary>
        public string CreateParameter
        {
            get
            {
                if (Interface.InnerModel.Name.EqualsIgnoreCase(Interface.CreatePayloadInnerModel.Name))
                {
                    return "this.inner()";
                }
                else if (Interface.CreatePayloadInnerModel.Name.EqualsIgnoreCase(Interface.UpdatePayloadInnerModel.Name))
                { 
                    return "this.createOrUpdateParameter";
                }
                else
                {
                   return "this.createParameter";
                }
            }
        }

        /// <summary>
        /// Return Java variable name (or accessor) used as the value of resource update inner call. 
        /// </summary>
        public string UpdateParameter
        {
            get
            {
                if (Interface.InnerModel.Name.EqualsIgnoreCase(Interface.UpdatePayloadInnerModel.Name))
                {
                    return "this.inner()";
                }
                else if (Interface.UpdatePayloadInnerModel.Name.EqualsIgnoreCase(Interface.CreatePayloadInnerModel.Name))
                {
                    return "this.createOrUpdateParameter";
                }
                else
                {
                    return "this.updateParameter";
                }
            }
        }

        /// <summary>
        /// Checks whether the inner type representing the payload of create and update inner method calls 
        /// are same.
        /// </summary>
        public bool IsCreateUpdateInnerTypeSame
        {
            get
            {
                string n1 = Interface.CreatePayloadInnerModel.Name;
                string n2 = Interface.UpdatePayloadInnerModel.Name;
                return n1.Equals(n2);
            }
        }

        /// <summary>
        /// Checks whether the inner method used to create and update the resource are same.
        /// </summary>
        public bool IsCreateUpdateInnerMethodSame
        {
            get
            {
                if (this.Interface.SupportsCreating)
                {
                    if (this.Interface.SupportsUpdating)
                    {
                        var createMethod = this.Interface.FluentMethodGroup.ResourceCreateDescription.CreateMethod;
                        var updateMethod = this.Interface.FluentMethodGroup.ResourceUpdateDescription.UpdateMethod;
                        return createMethod.Name.Equals(updateMethod.Name);
                    }
                    else
                    {
                        throw new InvalidOperationException("Should be called only if SupportsUpdating is true");
                    }
                }
                else if (this.Interface.SupportsUpdating)
                {
                    return false;
                }
                else
                {
                    throw new InvalidOperationException("Should be called only if SupportsUpdating is true");
                }
            }
        }

        /// <summary>
        /// The imports used by the groupable model implementation generated by this impl-metadata model.
        /// </summary>
        public HashSet<string> Imports
        {
            get
            {
                HashSet<string> imports = new HashSet<string>();
                imports.AddRange(this.Interface.PropertiesAndMethodImports.Where(imp => !imp.EndsWith("Inner")));
                imports.Add("com.microsoft.azure.management.resources.fluentcore.arm.models.implementation.GroupableResourceImpl");
                imports.Add($"{this.Interface.Package}.{this.Interface.JavaInterfaceName}");
                imports.Add("rx.Observable");
                if (this.RequireFlatmapAfterUpdate)
                {
                    imports.Add("rx.functions.Func1");
                }
                if (this.RequireFlatmapAfterCreate)
                {
                    imports.Add("rx.functions.Func1");
                }
                return imports;
            }
        }

        /// <summary>
        /// Returns the base type that the groupable model implementation inherits from.
        /// </summary>
        public string ExtendsFrom
        {
            get
            {
                return $" extends GroupableResourceImpl<{this.Interface.JavaInterfaceName}, " +
                    $"{this.Interface.InnerModel.Name}, " +
                    $"{this.JvaClassName}, " +
                    $"{this.Interface.FluentMethodGroup.ManagerTypeName}>";
            }
        }

        /// <summary>
        /// Returns the string representing the call to create the groupable resource.
        /// </summary>
        public string CreateInvocation
        {
            get
            {
                if (!this.Interface.SupportsCreating)
                {
                    return String.Empty;
                }

                FluentMethod createMethod = this.Interface.FluentMethodGroup.ResourceCreateDescription.CreateMethod;
                if (this.RequireFlatmapAfterCreate)
                {
                    string createReturnTypeName = createMethod.ReturnModel.InnerModel.Name;
                    string innerModelTypeName = this.InnerModelTypeName;

                    return $"client.{createMethod.InnerMethod.Name}Async(this.resourceGroupName(), this.name(), {this.CreateParameter})" +
                         $"\n        .flatMap(new Func1<{createReturnTypeName}, Observable<{innerModelTypeName}>>() {{" +
                         $"\n           @Override" +
                         $"\n           public Observable<{innerModelTypeName}> call({createReturnTypeName} r) {{ " +
                         $"\n               return getInnerAsync(); " +
                         $"\n           }} " +
                         $"\n        }})" +
                         $"\n        .map(innerToFluentMap(this))";
                }
                else
                {
                    return $"client.{createMethod.InnerMethod.Name}Async(this.resourceGroupName(), this.name(), {this.CreateParameter})" +
                        $"\n        .map(innerToFluentMap(this))";
                }
            }
        }


        /// <summary>
        /// Returns the string representing the call to update the groupable resource.
        /// </summary>
        public string UpdateInvocation
        {
            get
            {
                if (!this.Interface.SupportsUpdating)
                {
                    return String.Empty;
                }

                FluentMethod updateMethod = this.Interface.FluentMethodGroup.ResourceUpdateDescription.UpdateMethod;
                if (this.RequireFlatmapAfterUpdate)
                {
                    string updateReturnTypeName = updateMethod.ReturnModel.InnerModel.Name;
                    string innerModelTypeName = this.InnerModelTypeName;

                    return $"client.{updateMethod.InnerMethod.Name}Async(this.resourceGroupName(), this.name(), {this.UpdateParameter})" +
                         $"\n        .flatMap(new Func1<{updateReturnTypeName}, Observable<{innerModelTypeName}>>() {{" +
                         $"\n           @Override" +
                         $"\n           public Observable<{innerModelTypeName}> call({updateReturnTypeName} r) {{ " +
                         $"\n               return getInnerAsync(); " +
                         $"\n           }} " +
                         $"\n        }})" +
                         $"\n        .map(innerToFluentMap(this))";
                }
                else
                {
                    return $"client.{updateMethod.InnerMethod.Name}Async(this.resourceGroupName(), this.name(), {this.UpdateParameter})" +
                        $"\n        .map(innerToFluentMap(this))";
                }
            }
        }

        /// <summary>
        /// Checks a flatmap is needed after inner update call, this is needed if the return type of inner update
        /// and inner model are different.
        /// </summary>
        private bool RequireFlatmapAfterUpdate
        {
            get
            {
                if (!this.Interface.SupportsUpdating)
                {
                    return false;
                }
                FluentMethod updateMethod = this.Interface.FluentMethodGroup.ResourceUpdateDescription.UpdateMethod;
                string updateReturnTypeName = updateMethod.ReturnModel.InnerModel.Name;
                string innerModelTypeName = this.InnerModelTypeName;

                return !updateReturnTypeName.Equals(this.InnerModelTypeName);
            }
        }

        /// <summary>
        /// Checks a flatmap is needed after inner create call, this is needed if the return type of inner create
        /// and inner model are different.
        /// </summary>
        private bool RequireFlatmapAfterCreate
        {
            get
            {
                if (!this.Interface.SupportsCreating)
                {
                    return false;
                }
                FluentMethod createMethod = this.Interface.FluentMethodGroup.ResourceCreateDescription.CreateMethod;
                string createReturnTypeName = createMethod.ReturnModel.InnerModel.Name;
                string innerModelTypeName = this.InnerModelTypeName;
                return !createReturnTypeName.Equals(this.InnerModelTypeName);
            }
        }

        /// <summary>
        /// Returns the string representing the call to retrieve the groupable resource by resource group.
        /// </summary>
        public string GetInnerInvocation
        {
            get
            {
                if (!this.Interface.SupportsGetting)
                {
                    return String.Empty;
                }
                FluentMethod getMethod = this.Interface.FluentMethodGroup.ResourceGetDescription.GetByResourceGroupMethod;
                return $"client.{getMethod.InnerMethod.Name}Async(this.resourceGroupName(), this.name())";
            }
        }

        /// <summary>
        /// The interfaces that the groupable model implementation implements.
        /// </summary>
        public string Implements
        {
            get
            {
                List<string> implements = new List<string>
                {
                    this.Interface.JavaInterfaceName
                };
                if (this.Interface.SupportsCreating)
                {
                    implements.Add($"{this.Interface.JavaInterfaceName}.Definition");
                }
                if (this.Interface.SupportsUpdating)
                {
                    implements.Add($"{this.Interface.JavaInterfaceName}.Update");
                }
                if (implements.Count() > 0)
                {
                    return $" implements {String.Join(", ", implements)}";
                }
                else
                {
                    return String.Empty;
                }
            }
        }

        /// <summary>
        /// Returns the methods used to set the groupable resource properties applicable only during resource creation time.
        /// </summary>
        public IEnumerable<FluentDefinitionOrUpdateStageMethod> CreateOnlyWither
        {
            get
            {
                return this.Interface.RequiredDefinitionStages
                    .Union(this.Interface.OptionalDefinitionStages)
                    .SelectMany(s => s.Methods)
                    .Except(this.Interface.UpdateStages.SelectMany(r => r.Methods), FluentDefinitionOrUpdateStageMethod.EqualityComparer());
            }
        }

        /// <summary>
        /// Returns the methods used to set the groupable resource properties applicable only during resource update time.
        /// </summary>
        public IEnumerable<FluentDefinitionOrUpdateStageMethod> UpdateOnlyWithers
        {
            get
            {
                return this.Interface.UpdateStages
                     .SelectMany(s => s.Methods)
                     .Except(this.Interface.RequiredDefinitionStages.Union(this.Interface.OptionalDefinitionStages).SelectMany(r => r.Methods), FluentDefinitionOrUpdateStageMethod.EqualityComparer());
            }
        }

        /// <summary>
        /// Returns the methods used to set the groupable resource properties applicable for both resource creation and update time.
        /// </summary>
        public IEnumerable<FluentDefinitionOrUpdateStageMethod> CreateAndUpdateWithers
        {
            get
            {
                return this.Interface.RequiredDefinitionStages
                    .Union(this.Interface.OptionalDefinitionStages)
                    .SelectMany(s => s.Methods)
                    .Intersect(this.Interface.UpdateStages.SelectMany(u => u.Methods), FluentDefinitionOrUpdateStageMethod.EqualityComparer());
            }
        }

        public string CtrInvocationFromWrapExistingInnerModel
        {
            get
            {
                return $" new {JvaClassName}(inner.name(), inner, this.manager());";
            }
        }

        public string CtrInvocationFromWrapNewInnerModel
        {
            get
            {
                return $"new {JvaClassName}(name, new {InnerModelTypeName}(), this.manager());";
            }
        }
    }
}
