using AutoRest.Core.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AutoRest.Java.Azure.Fluent.Model
{
    /// <summary>
    /// The impl-metadata model that can generate a groupable model implementation.
    /// </summary>
    public class GroupableFluentModelImpl
    {

        public GroupableFluentModelImpl(GroupableFluentModelInterface mInterface)
        {
            this.Interface = mInterface;
        }

        /// <summary>
        /// Reference to the interface-metadata model rpresenting the groupable model 
        /// interface that is implemented by the model implementation generated by this
        /// impl-metadata model.
        /// </summary>
        public GroupableFluentModelInterface Interface
        {
            get; private set;
        }

        /// <summary>
        /// Name of the Java class this impl-metadata model generates.
        /// </summary>
        public string JvaClassName
        {
            get
            {
                return $"{this.Interface.JavaInterfaceName}Impl";
            }
        }

        /// <summary>
        /// The Java type of the inner model.
        /// </summary>
        public string InnerModelTypeName
        {
            get
            {
                return this.Interface.InnerModel.Name;
            }
        }

        /// <summary>
        /// The Java type of the inner method group (operation group).
        /// </summary>
        public string InnerMethodGroupTypeName
        {
            get
            {
                return this.Interface.FluentMethodGroup.InnerMethodGroup.MethodGroupImplType;
            }
        }

        public string CtrImplementation
        {
            get
            {
                StringBuilder methodBuilder = new StringBuilder();
                methodBuilder.AppendLine($"{JvaClassName}(String name, {InnerModelTypeName} inner, {this.Interface.FluentMethodGroup.ManagerTypeName} manager) {{");
                methodBuilder.AppendLine($"    super(name, inner, manager);");
                foreach(string initvariable in InitMemberVariables)
                {
                    methodBuilder.AppendLine($"    {initvariable}");
                }
                methodBuilder.AppendLine($"}}");
                return methodBuilder.ToString();
            }
        }

        public IEnumerable<string> DeclareMemberVariables
        {
            get
            {

                return this.Interface.DisambiguatedMemberVariables
                    .MemberVariables
                    .Where(v => !(v is FluentModelParentRefMemberVariable))
                    .Select(m => m.VariableDeclaration);
            }
        }

        public IEnumerable<string> InitMemberVariables
        {
            get
            {
                return this.Interface.DisambiguatedMemberVariables
                    .MemberVariables
                    .Select(m => m.VariableInitialize)
                    .Where(d => !string.IsNullOrEmpty(d));
            }
        }

        /// <summary>
        /// The imports used by the groupable model implementation generated by this impl-metadata model.
        /// </summary>
        public HashSet<string> Imports
        {
            get
            {
                HashSet<string> imports = new HashSet<string>();
                imports.Add("com.microsoft.azure.management.resources.fluentcore.arm.models.implementation.GroupableResourceImpl");
                imports.Add($"{this.Interface.Package}.{this.Interface.JavaInterfaceName}");
                imports.Add("rx.Observable");
                if (this.RequireFlatmapAfterUpdate || this.RequireFlatmapAfterCreate || this.Interface.RequirePayloadReset)
                {
                    imports.Add("rx.functions.Func1");
                }
                imports.AddRange(this.Interface.ImportsForImpl);
                return imports;
            }
        }

        /// <summary>
        /// Checks a flatmap is needed after inner update call, this is needed if the return type of inner update
        /// and inner model are different.
        /// </summary>
        private bool RequireFlatmapAfterUpdate
        {
            get
            {
                if (!this.Interface.SupportsUpdating)
                {
                    return false;
                }
                FluentMethod updateMethod = this.Interface.FluentMethodGroup.ResourceUpdateDescription.UpdateMethod;
                string updateReturnTypeName = updateMethod.ReturnModel.InnerModel.Name;
                string innerModelTypeName = this.InnerModelTypeName;

                return !updateReturnTypeName.Equals(this.InnerModelTypeName);
            }
        }

        /// <summary>
        /// Checks a flatmap is needed after inner create call, this is needed if the return type of inner create
        /// and inner model are different.
        /// </summary>
        private bool RequireFlatmapAfterCreate
        {
            get
            {
                if (!this.Interface.SupportsCreating)
                {
                    return false;
                }
                FluentMethod createMethod = this.Interface.FluentMethodGroup.ResourceCreateDescription.CreateMethod;
                string createReturnTypeName = createMethod.ReturnModel.InnerModel.Name;
                string innerModelTypeName = this.InnerModelTypeName;
                return !createReturnTypeName.Equals(this.InnerModelTypeName);
            }
        }

        public string ExtendsFrom
        {
            get
            {
                return $" extends GroupableResourceImpl<{this.Interface.JavaInterfaceName}, " +
                    $"{this.Interface.InnerModel.Name}, " +
                    $"{this.JvaClassName}, " +
                    $"{this.Interface.FluentMethodGroup.ManagerTypeName}>";
            }
        }

        public string Implements
        {
            get
            {
                List<string> implements = new List<string>
                {
                    this.Interface.JavaInterfaceName
                };
                if (this.Interface.SupportsCreating)
                {
                    implements.Add($"{this.Interface.JavaInterfaceName}.Definition");
                }
                if (this.Interface.SupportsUpdating)
                {
                    implements.Add($"{this.Interface.JavaInterfaceName}.Update");
                }
                if (implements.Count() > 0)
                {
                    return $" implements {String.Join(", ", implements)}";
                }
                else
                {
                    return String.Empty;
                }
            }
        }

        public IEnumerable<string> JavaMethods
        {
            get
            {
                yield return this.CtrImplementation;
                yield return CreatableUpdatableAbstractMethodsImplementation;
                if (this.Interface.IsCreatableOrUpdatable)
                {
                    StringBuilder methodsBuilder = new StringBuilder();
                    methodsBuilder.AppendLine("@Override");
                    methodsBuilder.AppendLine("public boolean isInCreateMode() {");
                    methodsBuilder.AppendLine("    return this.inner().id() == null;");
                    methodsBuilder.AppendLine("}");
                    yield return methodsBuilder.ToString();
                }
                yield return this.Interface.ResetRquestPayloadVariablesMethodImplementation;
            }
        }

        private string CreatableUpdatableAbstractMethodsImplementation
        {
            get
            {
                var createResourceAsyncMethod = this.CreateResourceAsyncMethodImplementation;
                var updateResourceAsyncMethod = this.UpdateResourceAsyncMethodImplementation;
                var getInnerAsyncMethod = this.GetInnerAsyncMethodImplementation;
                //
                return $"\n{createResourceAsyncMethod}\n\n{updateResourceAsyncMethod}\n\n{getInnerAsyncMethod}\n";
            }
        }

        private string CreateResourceAsyncMethodImplementation
        {
            get
            {
                StringBuilder methodBuilder = new StringBuilder();
                methodBuilder.AppendLine("@Override");
                methodBuilder.AppendLine($"public Observable<{this.Interface.JavaInterfaceName}> createResourceAsync() {{");
                methodBuilder.AppendLine($"    {Interface.FluentMethodGroup.InnerMethodGroup.MethodGroupImplType} client = this.manager().inner().{this.Interface.FluentMethodGroup.InnerMethodGroup.Name}();");
                if (!this.Interface.SupportsCreating)
                {
                    methodBuilder.AppendLine("    return null; // NOP createResourceAsync implementation as create is not supported");
                }
                else
                {
                    //
                    List<string> params1 = new List<string>()
                    {
                        "this.resourceGroupName()",
                        "this.name()"
                    };
                    //
                    IEnumerable<string> params2 = this.Interface.DisambiguatedMemberVariables.MemeberVariablesForCreate
                        .Values
                        .OrderBy(v => v.Index)
                        .Where(v => !(v is FluentModelParentRefMemberVariable))
                        .Select(v => v.VariableAccessor);
                    //
                    IEnumerable<string> createMethodParameters = params1.Union(params2);
                    //
                    var createMethodParametersCombined = String.Join(", ", createMethodParameters);

                    FluentMethod createMethod = this.Interface.FluentMethodGroup.ResourceCreateDescription.CreateMethod;
                    if (this.RequireFlatmapAfterCreate)
                    {
                        string createReturnTypeName = createMethod.ReturnModel.InnerModel.Name;
                        string innerModelTypeName = this.InnerModelTypeName;

                        methodBuilder.AppendLine($"return client.{createMethod.InnerMethod.Name}Async({createMethodParametersCombined})");
                        methodBuilder.AppendLine($"        .flatMap(new Func1<{createReturnTypeName}, Observable<{innerModelTypeName}>>() {{");
                        methodBuilder.AppendLine($"           @Override");
                        methodBuilder.AppendLine($"           public Observable<{innerModelTypeName}> call({createReturnTypeName} resource) {{");
                        if (this.Interface.RequirePayloadReset)
                        {
                            methodBuilder.AppendLine($"               {CreatableUpdatableModel.ResetCreateUpdateParametersMethodName}(); ");
                        }
                        methodBuilder.AppendLine($"               return getInnerAsync(); ");
                        methodBuilder.AppendLine($"           }} ");
                        methodBuilder.AppendLine($"        }})");
                        methodBuilder.AppendLine($"        .map(innerToFluentMap(this));");
                    }
                    else
                    {
                        string createReturnTypeName = createMethod.ReturnModel.InnerModel.Name;
                        string innerModelTypeName = this.InnerModelTypeName;

                        methodBuilder.AppendLine($"    return client.{createMethod.InnerMethod.Name}Async({createMethodParametersCombined})");
                        if (this.Interface.RequirePayloadReset)
                        {
                            methodBuilder.AppendLine($"        .map(new Func1<{innerModelTypeName}, {innerModelTypeName}>() {{");
                            methodBuilder.AppendLine($"           @Override");
                            methodBuilder.AppendLine($"           public {createReturnTypeName} call({createReturnTypeName} resource) {{");
                            methodBuilder.AppendLine($"               {CreatableUpdatableModel.ResetCreateUpdateParametersMethodName}(); ");
                            methodBuilder.AppendLine($"               return resource; ");
                            methodBuilder.AppendLine($"           }} ");
                            methodBuilder.AppendLine($"        }})");
                        }
                        methodBuilder.AppendLine($"        .map(innerToFluentMap(this));");
                    }
                }
                methodBuilder.AppendLine("}");
                return methodBuilder.ToString();
            }
        }

        private string UpdateResourceAsyncMethodImplementation
        {
            get
            {
                StringBuilder methodBuilder = new StringBuilder();
                methodBuilder.AppendLine("@Override");
                methodBuilder.AppendLine($"public Observable<{this.Interface.JavaInterfaceName}> updateResourceAsync() {{");
                methodBuilder.AppendLine($"    {Interface.FluentMethodGroup.InnerMethodGroup.MethodGroupImplType} client = this.manager().inner().{this.Interface.FluentMethodGroup.InnerMethodGroup.Name}();");
                if (!this.Interface.SupportsUpdating)
                {
                    methodBuilder.AppendLine("    return null; // NOP updateResourceAsync implementation as update is not supported");
                }
                else
                {
                    //
                    List<string> params1 = new List<string>()
                    {
                        "this.resourceGroupName()",
                        "this.name()"
                    };
                    //
                    IEnumerable<string> params2 = this.Interface.DisambiguatedMemberVariables.MemeberVariablesForUpdate
                        .Values
                        .OrderBy(v => v.Index)
                        .Where(v => !(v is FluentModelParentRefMemberVariable))
                        .Select(v => v.VariableAccessor);
                    //
                    IEnumerable<string> updateMethodParameters = params1.Union(params2);
                    //
                    var updateMethodParametersCombined = String.Join(", ", updateMethodParameters);

                    FluentMethod updateMethod = this.Interface.FluentMethodGroup.ResourceUpdateDescription.UpdateMethod;
                    if (this.RequireFlatmapAfterCreate)
                    {
                        string updateReturnTypeName = updateMethod.ReturnModel.InnerModel.Name;
                        string innerModelTypeName = this.InnerModelTypeName;

                        methodBuilder.AppendLine($"return client.{updateMethod.InnerMethod.Name}Async({updateMethodParametersCombined})");
                        methodBuilder.AppendLine($"        .flatMap(new Func1<{updateReturnTypeName}, Observable<{innerModelTypeName}>>() {{");
                        methodBuilder.AppendLine($"           @Override");
                        methodBuilder.AppendLine($"           public Observable<{innerModelTypeName}> call({updateReturnTypeName} r) {{");
                        if (this.Interface.RequirePayloadReset)
                        {
                            methodBuilder.AppendLine($"               {CreatableUpdatableModel.ResetCreateUpdateParametersMethodName}(); ");
                        }
                        methodBuilder.AppendLine($"               return getInnerAsync(); ");
                        methodBuilder.AppendLine($"           }} ");
                        methodBuilder.AppendLine($"        }})");
                        methodBuilder.AppendLine($"        .map(innerToFluentMap(this));");
                    }
                    else
                    {
                        string updateReturnTypeName = updateMethod.ReturnModel.InnerModel.Name;
                        string innerModelTypeName = this.InnerModelTypeName;

                        methodBuilder.AppendLine($"    return client.{updateMethod.InnerMethod.Name}Async({updateMethodParametersCombined})");
                        if (this.Interface.RequirePayloadReset)
                        {
                            methodBuilder.AppendLine($"        .map(new Func1<{innerModelTypeName}, {innerModelTypeName}>() {{");
                            methodBuilder.AppendLine($"           @Override");
                            methodBuilder.AppendLine($"           public {updateReturnTypeName} call({updateReturnTypeName} resource) {{");
                            methodBuilder.AppendLine($"               {CreatableUpdatableModel.ResetCreateUpdateParametersMethodName}(); ");
                            methodBuilder.AppendLine($"               return resource; ");
                            methodBuilder.AppendLine($"           }} ");
                            methodBuilder.AppendLine($"        }})");
                        }
                        methodBuilder.AppendLine($"        .map(innerToFluentMap(this));");
                    }
                }
                methodBuilder.AppendLine("}");
                return methodBuilder.ToString();
            }
        }

        /// <summary>
        /// Return Java code that implements IndexableRefreshableWrapperImpl::getInnerAsync() abstract method.
        /// </summary>
        private string GetInnerAsyncMethodImplementation
        {
            get
            {
                StringBuilder methodBuilder = new StringBuilder();
                methodBuilder.AppendLine("@Override");
                methodBuilder.AppendLine($"protected Observable<{InnerModelTypeName}> getInnerAsync() {{");
                methodBuilder.AppendLine($"    {Interface.FluentMethodGroup.InnerMethodGroup.MethodGroupImplType} client = this.manager().inner().{this.Interface.FluentMethodGroup.InnerMethodGroup.Name}();");
                if (!this.Interface.SupportsGetting)
                {
                    methodBuilder.AppendLine("    return null; // NOP getInnerAsync implementation as get is not supported");
                }
                else
                {
                    // var getMethodParameters = this.Interface.DisambiguatedMemberVariables.MemeberVariablesForGet
                    //    .OrderBy(v => v.Index)
                    //    .Select(v => v.VariableAccessor);
                    //
                    // var getMethodParametersCombined = String.Join(", ", getMethodParameters);

                    FluentMethod getMethod = this.Interface.FluentMethodGroup.ResourceGetDescription.GetByResourceGroupMethod;
                    methodBuilder.AppendLine($"    return client.{getMethod.InnerMethod.Name}Async(this.resourceGroupName(), this.name());");
                }
                methodBuilder.AppendLine("}");
                return methodBuilder.ToString();
            }
        }

        public string CtrInvocationFromWrapExistingInnerModel
        {
            get
            {
                return $" new {JvaClassName}(inner.name(), inner, this.manager());";
            }
        }

        public string CtrInvocationFromWrapNewInnerModel
        {
            get
            {
                return $"new {JvaClassName}(name, new {this.InnerModelTypeName}(), this.manager());";
            }
        }
    }
}
