using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AutoRest.Java.Azure.Fluent.Model
{
    public class NestedFluentModelImpl
    {
        public NestedFluentModelImpl(NestedFluentModelInterface mInterface)
        {
            this.Interface = mInterface;
        }

        /// <summary>
        /// Reference to the interface-metadata model rpresenting the nested model 
        /// interface that is implemented by the model implementation generated by this
        /// impl-metadata model.
        /// </summary>
        public NestedFluentModelInterface Interface
        {
            get; private set;
        }

        /// <summary>
        /// Name of the Java class this impl-metadata model generates.
        /// </summary>
        public string JvaClassName
        {
            get
            {
                return $"{this.Interface.JavaInterfaceName}Impl";
            }
        }

        /// <summary>
        /// The Java type of the inner model.
        /// </summary>
        public string InnerModelTypeName
        {
            get
            {
                return this.Interface.InnerModel.Name;
            }
        }

        /// <summary>
        /// The Java type of the inner method group (operation group).
        /// </summary>
        public string InnerMethodGroupTypeName
        {
            get
            {
                return this.Interface.FluentMethodGroup.InnerMethodGroup.MethodGroupImplType;
            }
        }

        /// <summary>
        /// Collection of strings where each string represents declaration of a member variable.
        /// </summary>
        public IEnumerable<string> DeclareMemberVariables
        {
            get
            {
                return this.Interface.DisambiguatedMemberVariables
                    .MemberVariables
                    .Select(m => m.VariableDeclaration);
            }
        }

        /// <summary>
        /// Collection of strings where each string represents initialization of composite memeber variable.
        /// </summary>
        public IEnumerable<string> InitMemberVariables
        {
            get
            {
                return this.Interface.DisambiguatedMemberVariables
                    .MemberVariables
                    .Select(m => m.VariableInitialize)
                    .Where(d => !string.IsNullOrEmpty(d));
            }
        }

        public IEnumerable<string> InitParentRefAndPosMemberVariablesFromId
        {
            get
            {
                if (this.RequiresIdParsing)
                {
                    var parentVars = this.Interface.DisambiguatedMemberVariables.MemberVariables.OfType<FluentModelParentRefMemberVariable>();
                    foreach (var parentVar in parentVars)
                    {
                        yield return $"{parentVar.VariableAccessor} = IdParsingUtils.getValueFromIdByName(inner.id(), \"{parentVar.ParentRefName}\");";
                    }

                    var posVars = this.Interface.DisambiguatedMemberVariables.MemberVariables.OfType<FluentModelPositionalPathMemberVariable>();
                    foreach (var posVar in posVars)
                    {
                        yield return $"{posVar.VariableAccessor} = IdParsingUtils.getValueFromIdByPosition(inner.id(), {posVar.Position});";
                    }
                }
                else
                {
                    yield break;
                }
            }
        }

        private bool RequiresIdParsing
        {
            get
            {
                return this.Interface.SupportsRefreshing || this.Interface.SupportsUpdating;
            }
        }

        public HashSet<string> Imports
        {
            get
            {
                HashSet<string> imports = new HashSet<string>();

                imports.Add($"{this.Interface.Package}.{this.Interface.JavaInterfaceName}");     // The nested model interface
                if (this.Interface.IsCreatableOrUpdatable)
                {
                    imports.Add("com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl");
                }
                else if (this.IsIndexableRefreshable)
                {
                    imports.Add("com.microsoft.azure.management.resources.fluentcore.model.implementation.IndexableRefreshableWrapperImpl");
                }
                else
                {
                    imports.Add("com.microsoft.azure.management.resources.fluentcore.model.implementation.WrapperImpl");
                }

                imports.Add("rx.Observable");
                imports.AddRange(this.Interface.ImportsForImpl);

                return imports;
            }
        }

        public string ExtendsFrom
        {
            get
            {
                if (this.Interface.IsCreatableOrUpdatable)
                {
                    return $" extends CreatableUpdatableImpl<{this.Interface.JavaInterfaceName}, {this.InnerModelTypeName}, {this.JvaClassName}>";
                }
                else if (this.IsIndexableRefreshable)
                {
                    return $" extends IndexableRefreshableWrapperImpl<{this.Interface.JavaInterfaceName}, {this.InnerModelTypeName}>";
                }
                else
                {
                    return $" extends WrapperImpl<{this.InnerModelTypeName}>";
                }
            }
        }

        public string Implements
        {
            get
            {
                List<string> implements = new List<string>
                {
                    this.Interface.JavaInterfaceName
                };
                if (this.Interface.SupportsCreating)
                {
                    implements.Add($"{this.Interface.JavaInterfaceName}.Definition");
                }
                if (this.Interface.SupportsUpdating)
                {
                    implements.Add($"{this.Interface.JavaInterfaceName}.Update");
                }
                if (implements.Count() > 0)
                {
                    return $" implements {String.Join(", ", implements)}";
                }
                else
                {
                    return String.Empty;
                }
            }
        }

        public IEnumerable<string> JavaMethods
        {
            get
            {
                yield return this.CtrImplementation;
                yield return this.ManagerGetterImplementation;
                yield return AbstractMethodsImplementation;
                if (this.Interface.IsCreatableOrUpdatable)
                {
                    StringBuilder methodsBuilder = new StringBuilder();
                    methodsBuilder.AppendLine("@Override");
                    methodsBuilder.AppendLine("public boolean isInCreateMode() {");
                    methodsBuilder.AppendLine("    return this.inner().id() == null;");
                    methodsBuilder.AppendLine("}");
                    yield return methodsBuilder.ToString();
                }
                yield return this.Interface.ResetRquestPayloadVariablesMethodImplementation;
            }
        }

        public String CtrInvocationFromWrapNewInnerModel
        {
            get
            {
                if (this.Interface.SupportsCreating)
                {
                    return $"new {this.JvaClassName}(name, this.manager());";
                }
                else
                {
                    return String.Empty;
                }
            }
        }

        public String CtrInvocationFromWrapExistingInnerModel
        {
            get
            {
                if (this.Interface.IsCreatableOrUpdatable)
                {
                    return $" new {this.JvaClassName}(inner, this.manager());";
                }
                else if (this.IsIndexableRefreshable)
                {
                    return $" new {this.JvaClassName}(inner, this.manager());";
                }
                else
                {
                    return $" new {this.JvaClassName}(inner, this.manager());";
                }
            }
        }

        /// <summary>
        /// The accessor string to access the local variable holding azure nested resource name.
        /// </summary>
        private string MemberVariableAccessorHoldingResourceName
        {
            get
            {
                return this.Interface.DisambiguatedMemberVariables
                    .MemberVariables
                    .OfType<FluentModelParentRefMemberVariable>()
                    .OrderBy(v => v.Index)  // TODO: Find a better way to derive resource param
                    .Select(v => v.VariableAccessor)
                    .Last();
            }
        }

        private string CtrImplementation
        {
            get
            {
                string managerTypeName = this.Interface.FluentMethodGroup.ManagerTypeName;
                if (this.Interface.IsCreatableOrUpdatable)
                {
                    StringBuilder methodBuilder = new StringBuilder();
                    //
                    // Ctr1 FooImpl(String name): The ctr invoked from 'Collection.define(name)'
                    //
                    methodBuilder.AppendLine($"{this.JvaClassName}(String name, {managerTypeName} manager) {{");
                    methodBuilder.AppendLine($"    super(name, new {this.InnerModelTypeName}());");               // CreatableUpdatableImpl(name, inner)
                    methodBuilder.AppendLine($"    this.manager = manager;");
                    methodBuilder.AppendLine($"    // Set resource name");
                    methodBuilder.AppendLine($"    {MemberVariableAccessorHoldingResourceName} = name;");
                    // init create update member variables
                    //
                    methodBuilder.AppendLine($"    //");
                    foreach (string initMemberVariable in this.InitMemberVariables)
                    {
                        methodBuilder.AppendLine($"    {initMemberVariable}");
                    }
                    methodBuilder.AppendLine($"}}");
                    //
                    methodBuilder.AppendLine("");
                    //
                    // Ctr2 FooImpl(FooInner inner, Manager manager): The ctr invoked to wrap inner model retrieved from "Collection.Get() and Collection.List()"
                    //
                    methodBuilder.AppendLine($"{this.JvaClassName}({this.InnerModelTypeName} inner, {managerTypeName} manager) {{");
                    methodBuilder.AppendLine($"    super(inner.name(), inner);");       // CreatableUpdatableImpl(name, inner)
                    methodBuilder.AppendLine($"    this.manager = manager;");
                    methodBuilder.AppendLine($"    // Set resource name");
                    methodBuilder.AppendLine($"    {MemberVariableAccessorHoldingResourceName} = inner.name();");
                    // Init member variables
                    methodBuilder.AppendLine($"    // resource ancestor names");
                    var parentVars = this.Interface.DisambiguatedMemberVariables.MemberVariables.OfType<FluentModelParentRefMemberVariable>();
                    foreach (var parentVar in parentVars)
                    {
                        methodBuilder.AppendLine($"    {parentVar.VariableAccessor} = IdParsingUtils.getValueFromIdByName(inner.id(), \"{parentVar.ParentRefName}\");");
                    }
                    var posVars = this.Interface.DisambiguatedMemberVariables.MemberVariables.OfType<FluentModelPositionalPathMemberVariable>();
                    foreach (var posVar in posVars)
                    {
                        methodBuilder.AppendLine($"    {posVar.VariableAccessor} = IdParsingUtils.getValueFromIdByPosition(inner.id(), {posVar.Position});");
                    }
                    methodBuilder.AppendLine($"    //");
                    // init create update member variables
                    foreach (string initMemberVariable in this.InitMemberVariables)
                    {
                        methodBuilder.AppendLine($"    {initMemberVariable}");
                    }
                    //
                    methodBuilder.AppendLine($"}}");
                    //
                    methodBuilder.AppendLine("");
                    //
                    return methodBuilder.ToString();
                }
                else if (this.IsIndexableRefreshable)
                {
                    StringBuilder methodBuilder = new StringBuilder();
                    methodBuilder.AppendLine($"{this.JvaClassName}({this.InnerModelTypeName} inner,  {managerTypeName} manager) {{");
                    methodBuilder.AppendLine($"    super(null, inner);"); // IndexableRefreshableWrapperImpl(key, inner)
                    methodBuilder.AppendLine($"    this.manager = manager;");
                    // Init member variables
                    //
                    var parentVars = this.Interface.DisambiguatedMemberVariables.MemberVariables.OfType<FluentModelParentRefMemberVariable>();
                    foreach (var parentVar in parentVars)
                    {
                        methodBuilder.AppendLine($"    {parentVar.VariableAccessor} = IdParsingUtils.getValueFromIdByName(inner.id(), \"{parentVar.ParentRefName}\");");
                    }
                    var posVars = this.Interface.DisambiguatedMemberVariables.MemberVariables.OfType<FluentModelPositionalPathMemberVariable>();
                    foreach (var posVar in posVars)
                    {
                        methodBuilder.AppendLine($"    {posVar.VariableAccessor} = IdParsingUtils.getValueFromIdByPosition(inner.id(), {posVar.Position});");
                    }
                    //
                    methodBuilder.AppendLine($"}}");
                    //
                    return methodBuilder.ToString();
                }
                else
                {
                    StringBuilder methodBuilder = new StringBuilder();
                    methodBuilder.AppendLine($"{this.JvaClassName}({this.InnerModelTypeName} inner,  {managerTypeName} manager) {{");
                    methodBuilder.AppendLine($"    super(inner);"); // WrapperImpl(inner)
                    methodBuilder.AppendLine($"    this.manager = manager;");
                    methodBuilder.AppendLine($"}}");
                    //
                    return methodBuilder.ToString();
                }
            }
        }

        public string DeclareManagerVariable
        {
            get
            {
                return $"private final {this.Interface.FluentMethodGroup.ManagerTypeName} manager;";
            }
        }

        /// <summary>
        /// Implement method to get manager.
        /// </summary>
        private string ManagerGetterImplementation
        {
            get
            {
                string managerTypeName = this.Interface.FluentMethodGroup.ManagerTypeName;
                StringBuilder methodBuilder = new StringBuilder();
                methodBuilder.AppendLine($"@Override");
                methodBuilder.AppendLine($"public {managerTypeName} manager() {{");
                methodBuilder.AppendLine($"    return this.manager;");
                methodBuilder.AppendLine($"}}");
                return methodBuilder.ToString();
            }
        }

        /// <summary>
        /// Implements the abstract methods from the super class.
        /// </summary>
        private string AbstractMethodsImplementation
        {
            get
            {
                if (this.Interface.IsCreatableOrUpdatable)
                {
                    return CreatableUpdatableAbstractMethodsImplementation;
                }
                else if (this.IsIndexableRefreshable)
                {
                    return IndexableRefreshableAbstractMethodImplementation;
                }
                else
                {
                    return String.Empty;
                }
            }
        }

        /// <summary>
        /// Implements the abstract methods in CreatableUpdatableImpl.
        /// </summary>
        private string CreatableUpdatableAbstractMethodsImplementation
        {
            get
            {
                var createResourceAsyncMethod = this.CreateResourceAsyncMethodImplementation;
                var updateResourceAsyncMethod = this.UpdateResourceAsyncMethodImplementation;
                var getInnerAsyncMethod = this.GetInnerAsyncMethodImplementation;
                //
                return $"\n{createResourceAsyncMethod}\n\n{updateResourceAsyncMethod}\n\n{getInnerAsyncMethod}\n";
            }
        }

        private string CreateResourceAsyncMethodImplementation
        {
            get
            {
                if (!this.Interface.SupportsCreating)
                {
                    return this.Interface.CreateResourceAsyncNOPMethodImplementation(this.Interface.JavaInterfaceName, 
                        Interface.FluentMethodGroup.InnerMethodGroup.MethodGroupImplType);
                }
                else
                {
                    FluentMethod createMethod = this.Interface.FluentMethodGroup.ResourceCreateDescription.CreateMethod;

                    var createMethodParameters = this.Interface.DisambiguatedMemberVariables.MemeberVariablesForCreate
                                                    .Values
                                                    .OrderBy(v => v.Index)
                                                    .Select(v => v.VariableAccessor);
                    var createMethodParametersCombined = String.Join(", ", createMethodParameters);

                    return this.Interface.CreateResourceAsyncMethodImplementation(createMethod,
                        createMethodParametersCombined,
                        this.Interface.JavaInterfaceName,
                        Interface.FluentMethodGroup.InnerMethodGroup.MethodGroupImplType);
                }
            }
        }

        private string UpdateResourceAsyncMethodImplementation
        {
            get
            {
                if (!this.Interface.SupportsUpdating)
                {
                    return this.Interface.UpdateResourceAsyncNOPMethodImplementation(this.Interface.JavaInterfaceName, 
                        Interface.FluentMethodGroup.InnerMethodGroup.MethodGroupImplType);
                }
                else
                {
                    FluentMethod updateMethod = this.Interface.FluentMethodGroup.ResourceUpdateDescription.UpdateMethod;

                    var updateMethodParameters = this.Interface.DisambiguatedMemberVariables.MemeberVariablesForUpdate
                                                    .Values
                                                    .OrderBy(v => v.Index)
                                                    .Select(v => v.VariableAccessor);
                    var updateMethodParametersCombined = String.Join(", ", updateMethodParameters);

                    return this.Interface.CreateResourceAsyncMethodImplementation(updateMethod,
                        updateMethodParametersCombined,
                        this.Interface.JavaInterfaceName,
                        Interface.FluentMethodGroup.InnerMethodGroup.MethodGroupImplType);
                }
            }
        }

        /// <summary>
        /// Return Java code that implements IndexableRefreshableWrapperImpl::getInnerAsync() abstract method.
        /// </summary>
        private string GetInnerAsyncMethodImplementation
        {
            get
            {
                StringBuilder methodBuilder = new StringBuilder();
                methodBuilder.AppendLine("@Override");
                methodBuilder.AppendLine($"protected Observable<{InnerModelTypeName}> getInnerAsync() {{");
                methodBuilder.AppendLine($"    {Interface.FluentMethodGroup.InnerMethodGroup.MethodGroupImplType} client = this.manager.inner().{this.Interface.FluentMethodGroup.InnerMethodGroup.Name}();");
                if (!this.Interface.SupportsGetting)
                {
                    methodBuilder.AppendLine("    return null; // NOP getInnerAsync implementation as get is not supported");
                }
                else
                {
                    var getMethodParameters = this.Interface.DisambiguatedMemberVariables.MemeberVariablesForGet
                        .OrderBy(v => v.Index)
                        .Select(v => v.VariableAccessor);

                    var getMethodParametersCombined = String.Join(", ", getMethodParameters);

                    FluentMethod getMethod = this.Interface.FluentMethodGroup.ResourceGetDescription.GetByImmediateParentMethod;
                    methodBuilder.AppendLine($"    return client.{getMethod.InnerMethod.Name}Async({getMethodParametersCombined});");
                }
                methodBuilder.AppendLine("}");
                return methodBuilder.ToString();
            }
        }

        /// <summary>
        /// Implements the abstract methods in IndexableRefreshableImpl.
        /// </summary>
        private string IndexableRefreshableAbstractMethodImplementation
        {
            get
            {
                return GetInnerAsyncMethodImplementation;
            }
        }

        /// <summary>
        /// Checks the nested model is indexable & refreshable.
        /// </summary>
        private bool IsIndexableRefreshable
        {
            get
            {
                return this.Interface.SupportsRefreshing;
            }
        }
    }
}
