using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AutoRest.Java.Azure.Fluent.Model
{
    public class NestedFluentModelImpl
    {
        private const string resetCreateUpdateParametersMethodName = "resetCreateUpdateParameters";

        public NestedFluentModelImpl(NestedFluentModelInterface mInterface)
        {
            this.Interface = mInterface;
        }

        /// <summary>
        /// Reference to the interface-metadata model rpresenting the nested model 
        /// interface that is implemented by the model implementation generated by this
        /// impl-metadata model.
        /// </summary>
        public NestedFluentModelInterface Interface
        {
            get; private set;
        }

        /// <summary>
        /// Name of the Java class this impl-metadata model generates.
        /// </summary>
        public string JvaClassName
        {
            get
            {
                return $"{this.Interface.JavaInterfaceName}Impl";
            }
        }

        /// <summary>
        /// The Java type of the inner model.
        /// </summary>
        public string InnerModelTypeName
        {
            get
            {
                return this.Interface.InnerModel.Name;
            }
        }

        /// <summary>
        /// The Java type of the inner method group (operation group).
        /// </summary>
        public string InnerMethodGroupTypeName
        {
            get
            {
                return this.Interface.FluentMethodGroup.InnerMethodGroup.MethodGroupImplType;
            }
        }

        /// <summary>
        /// Collection of strings where each string represents declaration of a memeber variable.
        /// </summary>
        public IEnumerable<string> DeclareMemberVariables
        {
            get
            {
                return this.Interface.DisambiguatedMemberVariables
                    .MemberVariables
                    .Select(m => m.VariableDeclaration);
            }
        }

        /// <summary>
        /// Collection of strings where each string represents initialization of composite memeber variable.
        /// </summary>
        public IEnumerable<string> InitMemberVariables
        {
            get
            {
                return this.Interface.DisambiguatedMemberVariables
                    .MemberVariables
                    .Select(m => m.VariableInitialize)
                    .Where(d => !string.IsNullOrEmpty(d));
            }
        }

        public IEnumerable<string> InitParentRefAndPosMemberVariablesFromId
        {
            get
            {
                if (this.RequiresIdParsing)
                {
                    var parentVars = this.Interface.DisambiguatedMemberVariables.MemberVariables.OfType<FluentModelParentRefMemberVariable>();
                    foreach (var parentVar in parentVars)
                    {
                        yield return $"{parentVar.VariableAccessor} = IdParsingUtils.getValueFromIdByName(inner.id(), \"{parentVar.ParentRefName}\");";
                    }

                    var posVars = this.Interface.DisambiguatedMemberVariables.MemberVariables.OfType<FluentModelPositionalPathMemberVariable>();
                    foreach (var posVar in posVars)
                    {
                        yield return $"{posVar.VariableAccessor} = IdParsingUtils.getValueFromIdByPosition(inner.id(), {posVar.Position});";
                    }
                }
                else
                {
                    yield break;
                }
            }
        }

        private bool RequiresIdParsing
        {
            get
            {
                return this.Interface.SupportsRefreshing || this.Interface.SupportsUpdating;
            }
        }

        public HashSet<string> Imports
        {
            get
            {
                HashSet<string> imports = new HashSet<string>();

                imports.Add($"{this.Interface.Package}.{this.Interface.JavaInterfaceName}");     // The nested model interface
                if (this.IsCreatableOrUpdatable)
                {
                    imports.Add("com.microsoft.azure.management.resources.fluentcore.model.implementation.CreatableUpdatableImpl");
                }
                else if (this.IsIndexableRefreshable)
                {
                    imports.Add("com.microsoft.azure.management.resources.fluentcore.model.implementation.IndexableRefreshableWrapperImpl");
                }
                else
                {
                    imports.Add("com.microsoft.azure.management.resources.fluentcore.model.implementation.WrapperImpl");
                }

                imports.Add("rx.Observable");
                if (this.RequireFlatmapAfterUpdate || this.RequireFlatmapAfterCreate || this.RequirePayloadReset)
                {
                    imports.Add("rx.functions.Func1");
                }

                imports.AddRange(this.Interface.UpdateMemberVariablesImports.Where(impl => !impl.EndsWith("Inner")));
                imports.AddRange(this.Interface.CreateMemberVariablesImports.Where(impl => !impl.EndsWith("Inner")));
                imports.AddRange(this.Interface.LocalPropertiesImports.Where(imp => !imp.EndsWith("Inner")));

                return imports;
            }
        }

        /// <summary>
        /// The base type that the nested model impl extends from.
        /// </summary>
        public string ExtendsFrom
        {
            get
            {
                if (this.IsCreatableOrUpdatable)
                {
                    return $" extends CreatableUpdatableImpl<{this.Interface.JavaInterfaceName}, {this.InnerModelTypeName}, {this.JvaClassName}>";
                }
                else if (this.IsIndexableRefreshable)
                {
                    return $" extends IndexableRefreshableWrapperImpl<{this.Interface.JavaInterfaceName}, {this.InnerModelTypeName}>";
                }
                else
                {
                    return $" extends WrapperImpl<{this.InnerModelTypeName}>";
                }
            }
        }

        public string Implements
        {
            get
            {
                List<string> implements = new List<string>
                {
                    this.Interface.JavaInterfaceName
                };
                if (this.Interface.SupportsCreating)
                {
                    implements.Add($"{this.Interface.JavaInterfaceName}.Definition");
                }
                if (this.Interface.SupportsUpdating)
                {
                    implements.Add($"{this.Interface.JavaInterfaceName}.Update");
                }
                if (implements.Count() > 0)
                {
                    return $" implements {String.Join(", ", implements)}";
                }
                else
                {
                    return String.Empty;
                }
            }
        }

        public IEnumerable<string> JavaMethods
        {
            get
            {
                yield return this.CtrImplementation;
                yield return this.ManagerGetterImplementation;
                yield return AbstractMethodsImplementation;
                if (this.IsCreatableOrUpdatable)
                {
                    StringBuilder methodsBuilder = new StringBuilder();
                    methodsBuilder.AppendLine("@Override");
                    methodsBuilder.AppendLine("public boolean isInCreateMode() {");
                    methodsBuilder.AppendLine("    return this.inner().id() == null;");
                    methodsBuilder.AppendLine("}");
                    yield return methodsBuilder.ToString();
                }
                yield return MethodToResetRquestPayload;
            }
        }

        public String CtrInvocationFromWrapNewInnerModel
        {
            get
            {
                if (this.Interface.SupportsCreating)
                {
                    return $"new {this.JvaClassName}(name, this.manager());";
                }
                else
                {
                    return String.Empty;
                }
            }
        }

        public String CtrInvocationFromWrapExistingInnerModel
        {
            get
            {
                if (this.IsCreatableOrUpdatable)
                {
                    return $" new {this.JvaClassName}(inner, this.manager());";
                }
                else if (this.IsIndexableRefreshable)
                {
                    return $" new {this.JvaClassName}(inner, this.manager());";
                }
                else
                {
                    return $" new {this.JvaClassName}(inner, this.manager());";
                }
            }
        }

        /// <summary>
        /// The accessor string to access the local variable holding azure nested resource name.
        /// </summary>
        private string MemberVariableAccessorHoldingResourceName
        {
            get
            {
                return this.Interface.DisambiguatedMemberVariables
                    .MemberVariables
                    .OfType<FluentModelParentRefMemberVariable>()
                    .OrderBy(v => v.Index)  // TODO: Find a better way to derive resource param
                    .Select(v => v.VariableAccessor)
                    .Last();
            }
        }

        private string CtrImplementation
        {
            get
            {
                string managerTypeName = this.Interface.FluentMethodGroup.ManagerTypeName;
                if (this.IsCreatableOrUpdatable)
                {
                    StringBuilder methodBuilder = new StringBuilder();
                    //
                    // Ctr1 FooImpl(String name): The ctr invoked from 'Collection.define(name)'
                    //
                    methodBuilder.AppendLine($"{this.JvaClassName}(String name, {managerTypeName} manager) {{");
                    methodBuilder.AppendLine($"    super(name, new {this.InnerModelTypeName}());");               // CreatableUpdatableImpl(name, inner)
                    methodBuilder.AppendLine($"    this.manager = manager;");
                    methodBuilder.AppendLine($"    // Set resource name");
                    methodBuilder.AppendLine($"    {MemberVariableAccessorHoldingResourceName} = name;");
                    // init create update member variables
                    //
                    methodBuilder.AppendLine($"    //");
                    foreach (string initMemberVariable in this.InitMemberVariables)
                    {
                        methodBuilder.AppendLine($"    {initMemberVariable}");
                    }
                    methodBuilder.AppendLine($"}}");
                    //
                    methodBuilder.AppendLine("");
                    //
                    // Ctr2 FooImpl(FooInner inner, Manager manager): The ctr invoked to wrap inner model retrieved from "Collection.Get() and Collection.List()"
                    //
                    methodBuilder.AppendLine($"{this.JvaClassName}({this.InnerModelTypeName} inner, {managerTypeName} manager) {{");
                    methodBuilder.AppendLine($"    super(inner.name(), inner);");       // CreatableUpdatableImpl(name, inner)
                    methodBuilder.AppendLine($"    this.manager = manager;");
                    methodBuilder.AppendLine($"    // Set resource name");
                    methodBuilder.AppendLine($"    {MemberVariableAccessorHoldingResourceName} = inner.name();");
                    // Init member variables
                    methodBuilder.AppendLine($"    // resource ancestor names");
                    var parentVars = this.Interface.DisambiguatedMemberVariables.MemberVariables.OfType<FluentModelParentRefMemberVariable>();
                    foreach (var parentVar in parentVars)
                    {
                        methodBuilder.AppendLine($"    {parentVar.VariableAccessor} = IdParsingUtils.getValueFromIdByName(inner.id(), \"{parentVar.ParentRefName}\");");
                    }
                    var posVars = this.Interface.DisambiguatedMemberVariables.MemberVariables.OfType<FluentModelPositionalPathMemberVariable>();
                    foreach (var posVar in posVars)
                    {
                        methodBuilder.AppendLine($"    {posVar.VariableAccessor} = IdParsingUtils.getValueFromIdByPosition(inner.id(), {posVar.Position});");
                    }
                    methodBuilder.AppendLine($"    //");
                    // init create update member variables
                    foreach (string initMemberVariable in this.InitMemberVariables)
                    {
                        methodBuilder.AppendLine($"    {initMemberVariable}");
                    }
                    //
                    methodBuilder.AppendLine($"}}");
                    //
                    methodBuilder.AppendLine("");
                    //
                    return methodBuilder.ToString();
                }
                else if (this.IsIndexableRefreshable)
                {
                    StringBuilder methodBuilder = new StringBuilder();
                    methodBuilder.AppendLine($"{this.JvaClassName}({this.InnerModelTypeName} inner,  {managerTypeName} manager) {{");
                    methodBuilder.AppendLine($"    super(null, inner);"); // IndexableRefreshableWrapperImpl(key, inner)
                    methodBuilder.AppendLine($"    this.manager = manager;");
                    // Init member variables
                    //
                    var parentVars = this.Interface.DisambiguatedMemberVariables.MemberVariables.OfType<FluentModelParentRefMemberVariable>();
                    foreach (var parentVar in parentVars)
                    {
                        methodBuilder.AppendLine($"    {parentVar.VariableAccessor} = IdParsingUtils.getValueFromIdByName(inner.id(), \"{parentVar.ParentRefName}\");");
                    }
                    var posVars = this.Interface.DisambiguatedMemberVariables.MemberVariables.OfType<FluentModelPositionalPathMemberVariable>();
                    foreach (var posVar in posVars)
                    {
                        methodBuilder.AppendLine($"    {posVar.VariableAccessor} = IdParsingUtils.getValueFromIdByPosition(inner.id(), {posVar.Position});");
                    }
                    //
                    methodBuilder.AppendLine($"}}");
                    //
                    return methodBuilder.ToString();
                }
                else
                {
                    StringBuilder methodBuilder = new StringBuilder();
                    methodBuilder.AppendLine($"{this.JvaClassName}({this.InnerModelTypeName} inner,  {managerTypeName} manager) {{");
                    methodBuilder.AppendLine($"    super(inner);"); // WrapperImpl(inner)
                    methodBuilder.AppendLine($"    this.manager = manager;");
                    methodBuilder.AppendLine($"}}");
                    //
                    return methodBuilder.ToString();
                }
            }
        }

        public string DeclareManagerVariable
        {
            get
            {
                return $"private final {this.Interface.FluentMethodGroup.ManagerTypeName} manager;";
            }
        }

        /// <summary>
        /// Implement method to get manager.
        /// </summary>
        private string ManagerGetterImplementation
        {
            get
            {
                string managerTypeName = this.Interface.FluentMethodGroup.ManagerTypeName;
                StringBuilder methodBuilder = new StringBuilder();
                methodBuilder.AppendLine($"@Override");
                methodBuilder.AppendLine($"public {managerTypeName} manager() {{");
                methodBuilder.AppendLine($"    return this.manager;");
                methodBuilder.AppendLine($"}}");
                return methodBuilder.ToString();
            }
        }

        /// <summary>
        /// Implements the abstract methods from the super class.
        /// </summary>
        private string AbstractMethodsImplementation
        {
            get
            {
                if (this.IsCreatableOrUpdatable)
                {
                    return CreatableUpdatableAbstractMethodsImplementation;
                }
                else if (this.IsIndexableRefreshable)
                {
                    return IndexableRefreshableAbstractMethodImplementation;
                }
                else
                {
                    return String.Empty;
                }
            }
        }

        /// <summary>
        /// Implements the abstract methods in CreatableUpdatableImpl.
        /// </summary>
        private string CreatableUpdatableAbstractMethodsImplementation
        {
            get
            {
                var createResourceAsyncMethod = this.CreateResourceAsyncMethodImplementation;
                var updateResourceAsyncMethod = this.UpdateResourceAsyncMethodImplementation;
                var getInnerAsyncMethod = this.GetInnerAsyncMethodImplementation;
                //
                return $"\n{createResourceAsyncMethod}\n\n{updateResourceAsyncMethod}\n\n{getInnerAsyncMethod}\n";
            }
        }

        /// <summary>
        /// Return Java code that implements CreatableUpdatableImpl::createResourceAsync() abstract method.
        /// </summary>
        private string CreateResourceAsyncMethodImplementation
        {
            get
            {
                StringBuilder methodBuilder = new StringBuilder();
                methodBuilder.AppendLine("@Override");
                methodBuilder.AppendLine($"public Observable<{this.Interface.JavaInterfaceName}> createResourceAsync() {{");
                methodBuilder.AppendLine($"    {Interface.FluentMethodGroup.InnerMethodGroup.MethodGroupImplType} client = this.manager.inner().{this.Interface.FluentMethodGroup.InnerMethodGroup.Name}();");
                if (!this.Interface.SupportsCreating)
                {
                    methodBuilder.AppendLine("    return null; // NOP createResourceAsync implementation as create is not supported");
                }
                else
                {
                    var createMethodParameters = this.Interface.DisambiguatedMemberVariables.MemeberVariablesForCreate
                        .Values
                        .OrderBy(v => v.Index)
                        .Select(v => v.VariableAccessor);
                    var createMethodParametersCombined = String.Join(", ", createMethodParameters);

                    FluentMethod createMethod = this.Interface.FluentMethodGroup.ResourceCreateDescription.CreateMethod;
                    if (this.RequireFlatmapAfterCreate)
                    {
                        string createReturnTypeName = createMethod.ReturnModel.InnerModel.Name;
                        string innerModelTypeName = this.InnerModelTypeName;

                        methodBuilder.AppendLine($"return client.{createMethod.InnerMethod.Name}Async({createMethodParametersCombined})");
                        methodBuilder.AppendLine($"        .flatMap(new Func1<{createReturnTypeName}, Observable<{innerModelTypeName}>>() {{");
                        methodBuilder.AppendLine($"           @Override");
                        methodBuilder.AppendLine($"           public Observable<{innerModelTypeName}> call({createReturnTypeName} resource) {{");
                        if (RequirePayloadReset)
                        {
                            methodBuilder.AppendLine($"               {resetCreateUpdateParametersMethodName}(); ");
                        }
                        methodBuilder.AppendLine($"               return getInnerAsync(); ");
                        methodBuilder.AppendLine($"           }} ");
                        methodBuilder.AppendLine($"        }})");
                        methodBuilder.AppendLine($"        .map(innerToFluentMap(this));");
                    }
                    else
                    {
                        string createReturnTypeName = createMethod.ReturnModel.InnerModel.Name;
                        string innerModelTypeName = this.InnerModelTypeName;

                        methodBuilder.AppendLine($"    return client.{createMethod.InnerMethod.Name}Async({createMethodParametersCombined})");
                        if (RequirePayloadReset)
                        {
                            methodBuilder.AppendLine($"        .map(new Func1<{innerModelTypeName}, {innerModelTypeName}>() {{");
                            methodBuilder.AppendLine($"           @Override");
                            methodBuilder.AppendLine($"           public {createReturnTypeName} call({createReturnTypeName} resource) {{");
                            methodBuilder.AppendLine($"               {resetCreateUpdateParametersMethodName}(); ");
                            methodBuilder.AppendLine($"               return resource; ");
                            methodBuilder.AppendLine($"           }} ");
                            methodBuilder.AppendLine($"        }})");
                        }
                        methodBuilder.AppendLine($"        .map(innerToFluentMap(this));");
                    }
                }
                methodBuilder.AppendLine("}");
                return methodBuilder.ToString();
            }
        }

        /// <summary>
        /// Checks a flatmap is needed after inner create call, this is needed if the return type of inner create
        /// and inner model are different.
        /// </summary>
        private bool RequireFlatmapAfterCreate
        {
            get
            {
                if (!this.Interface.SupportsCreating)
                {
                    return false;
                }
                FluentMethod createMethod = this.Interface.FluentMethodGroup.ResourceCreateDescription.CreateMethod;
                string createReturnTypeName = createMethod.ReturnModel.InnerModel.Name;
                string innerModelTypeName = this.InnerModelTypeName;
                return !createReturnTypeName.Equals(this.InnerModelTypeName);
            }
        }

        /// <summary>
        /// Return Java code that implements CreatableUpdatableImpl::updateResourceAsync() abstract method.
        /// </summary>
        private string UpdateResourceAsyncMethodImplementation
        {
            get
            {
                StringBuilder methodBuilder = new StringBuilder();
                methodBuilder.AppendLine("@Override");
                methodBuilder.AppendLine($"public Observable<{this.Interface.JavaInterfaceName}> updateResourceAsync() {{");
                methodBuilder.AppendLine($"    {Interface.FluentMethodGroup.InnerMethodGroup.MethodGroupImplType} client = this.manager.inner().{this.Interface.FluentMethodGroup.InnerMethodGroup.Name}();");
                if (!this.Interface.SupportsUpdating)
                {
                    methodBuilder.AppendLine("    return null; // NOP updateResourceAsync implementation as update is not supported");
                }
                else
                {
                    var updateMethodParameters = this.Interface.DisambiguatedMemberVariables.MemeberVariablesForUpdate
                        .Values
                        .OrderBy(v => v.Index)
                        .Select(v => v.VariableAccessor);
                    var updateMethodParametersCombined = String.Join(", ", updateMethodParameters);

                    FluentMethod updateMethod = this.Interface.FluentMethodGroup.ResourceUpdateDescription.UpdateMethod;
                    if (this.RequireFlatmapAfterCreate)
                    {
                        string updateReturnTypeName = updateMethod.ReturnModel.InnerModel.Name;
                        string innerModelTypeName = this.InnerModelTypeName;

                        methodBuilder.AppendLine($"return client.{updateMethod.InnerMethod.Name}Async({updateMethodParametersCombined})");
                        methodBuilder.AppendLine($"        .flatMap(new Func1<{updateReturnTypeName}, Observable<{innerModelTypeName}>>() {{");
                        methodBuilder.AppendLine($"           @Override");
                        methodBuilder.AppendLine($"           public Observable<{innerModelTypeName}> call({updateReturnTypeName} r) {{");
                        if (RequirePayloadReset)
                        {
                            methodBuilder.AppendLine($"               {resetCreateUpdateParametersMethodName}(); ");
                        }
                        methodBuilder.AppendLine($"               return getInnerAsync(); ");
                        methodBuilder.AppendLine($"           }} ");
                        methodBuilder.AppendLine($"        }})");
                        methodBuilder.AppendLine($"        .map(innerToFluentMap(this));");
                    }
                    else
                    {
                        string updateReturnTypeName = updateMethod.ReturnModel.InnerModel.Name;
                        string innerModelTypeName = this.InnerModelTypeName;

                        methodBuilder.AppendLine($"    return client.{updateMethod.InnerMethod.Name}Async({updateMethodParametersCombined})");
                        if (RequirePayloadReset)
                        {
                            methodBuilder.AppendLine($"        .map(new Func1<{innerModelTypeName}, {innerModelTypeName}>() {{");
                            methodBuilder.AppendLine($"           @Override");
                            methodBuilder.AppendLine($"           public {updateReturnTypeName} call({updateReturnTypeName} resource) {{");
                            methodBuilder.AppendLine($"               {resetCreateUpdateParametersMethodName}(); ");
                            methodBuilder.AppendLine($"               return resource; ");
                            methodBuilder.AppendLine($"           }} ");
                            methodBuilder.AppendLine($"        }})");
                        }
                        methodBuilder.AppendLine($"        .map(innerToFluentMap(this));");
                    }
                }
                methodBuilder.AppendLine("}");
                return methodBuilder.ToString();
            }
        }

        /// <summary>
        /// Checks a flatmap is needed after inner update call, this is needed if the return type of inner update
        /// and inner model are different.
        /// </summary>
        private bool RequireFlatmapAfterUpdate
        {
            get
            {
                if (!this.Interface.SupportsUpdating)
                {
                    return false;
                }
                FluentMethod updateMethod = this.Interface.FluentMethodGroup.ResourceUpdateDescription.UpdateMethod;
                string updateReturnTypeName = updateMethod.ReturnModel.InnerModel.Name;
                string innerModelTypeName = this.InnerModelTypeName;

                return !updateReturnTypeName.Equals(this.InnerModelTypeName);
            }
        }

        /// <summary>
        /// Return Java code that implements IndexableRefreshableWrapperImpl::getInnerAsync() abstract method.
        /// </summary>
        private string GetInnerAsyncMethodImplementation
        {
            get
            {
                StringBuilder methodBuilder = new StringBuilder();
                methodBuilder.AppendLine("@Override");
                methodBuilder.AppendLine($"protected Observable<{InnerModelTypeName}> getInnerAsync() {{");
                methodBuilder.AppendLine($"    {Interface.FluentMethodGroup.InnerMethodGroup.MethodGroupImplType} client = this.manager.inner().{this.Interface.FluentMethodGroup.InnerMethodGroup.Name}();");
                if (!this.Interface.SupportsGetting)
                {
                    methodBuilder.AppendLine("    return null; // NOP getInnerAsync implementation as get is not supported");
                }
                else
                {
                    var getMethodParameters = this.Interface.DisambiguatedMemberVariables.MemeberVariablesForGet
                        .OrderBy(v => v.Index)
                        .Select(v => v.VariableAccessor);

                    var getMethodParametersCombined = String.Join(", ", getMethodParameters);

                    FluentMethod getMethod = this.Interface.FluentMethodGroup.ResourceGetDescription.GetByImmediateParentMethod;
                    methodBuilder.AppendLine($"    return client.{getMethod.InnerMethod.Name}Async({getMethodParametersCombined});");
                }
                methodBuilder.AppendLine("}");
                return methodBuilder.ToString();
            }
        }

        /// <summary>
        /// Implements the abstract methods in IndexableRefreshableImpl.
        /// </summary>
        private string IndexableRefreshableAbstractMethodImplementation
        {
            get
            {
                return GetInnerAsyncMethodImplementation;
            }
        }

        private string MethodToResetRquestPayload
        {
            get
            {
                var payloadMemberVariableInits = this.Interface.DisambiguatedMemberVariables
                    .MemberVariables
                    .Select(m => m.VariableInitialize)
                    .Where(d => !string.IsNullOrEmpty(d));

                if (payloadMemberVariableInits.Any())
                {
                    StringBuilder methodBuilder = new StringBuilder();

                    methodBuilder.AppendLine($"private void {resetCreateUpdateParametersMethodName}() {{");
                    foreach (var varInit in payloadMemberVariableInits)
                    {
                        methodBuilder.AppendLine($"    {varInit}");
                    }
                    methodBuilder.AppendLine($"}}");
                    return methodBuilder.ToString();
                }
                else
                {
                    return String.Empty;
                }
            }
        }

        private bool RequirePayloadReset
        {
            get
            {
                return this.Interface.DisambiguatedMemberVariables
                    .MemberVariables
                    .Select(m => m.VariableInitialize)
                    .Where(d => !string.IsNullOrEmpty(d))
                    .Any();
            }
        }


        /// <summary>
        /// Check the nested model is creatable or updatable.
        /// </summary>
        private bool IsCreatableOrUpdatable
        {
            get
            {
                return (this.Interface.SupportsCreating || this.Interface.SupportsUpdating);
            }
        }

        /// <summary>
        /// Checks the nested model is indexable & refreshable.
        /// </summary>
        private bool IsIndexableRefreshable
        {
            get
            {
                return this.Interface.SupportsRefreshing;
            }
        }



        /// <summary>
        /// Returns the methods used to set the nested resource properties applicable only during resource creation time.
        /// </summary>
        public IEnumerable<FluentDefinitionOrUpdateStageMethod> CreateOnlyWither
        {
            get
            {
                return this.Interface.RequiredDefinitionStages
                    .Union(this.Interface.OptionalDefinitionStages)
                    .SelectMany(s => s.Methods)
                    .Except(this.Interface.UpdateStages.SelectMany(r => r.Methods), FluentDefinitionOrUpdateStageMethod.EqualityComparer());
            }
        }

        /// <summary>
        /// Returns the methods used to set the nested resource properties applicable only during resource update time.
        /// </summary>
        public IEnumerable<FluentDefinitionOrUpdateStageMethod> UpdateOnlyWithers
        {
            get
            {
                return this.Interface.UpdateStages
                     .SelectMany(s => s.Methods)
                     .Except(this.Interface.RequiredDefinitionStages.Union(this.Interface.OptionalDefinitionStages).SelectMany(r => r.Methods), FluentDefinitionOrUpdateStageMethod.EqualityComparer());
            }
        }

        /// <summary>
        /// Returns the methods used to set the nested resource properties applicable for both resource creation and update time.
        /// </summary>
        public IEnumerable<FluentDefinitionOrUpdateStageMethod> CreateAndUpdateWithers
        {
            get
            {
                var defMethods = this.Interface.RequiredDefinitionStages
                    .Union(this.Interface.OptionalDefinitionStages)
                    .SelectMany(s => s.Methods);

                var updateMethods = this.Interface.UpdateStages
                    .SelectMany(u => u.Methods);

                var comparer = FluentDefinitionOrUpdateStageMethod.EqualityComparer();
                foreach (var defMethod in defMethods)
                {
                    foreach (var updateMethod in updateMethods)
                    {
                        if (comparer.Equals(defMethod, updateMethod))
                        {
                            if (defMethod.Body.Equals(updateMethod.Body))
                            {
                                yield return defMethod; // or updateMethod
                            }
                            else
                            {
                                FluentDefinitionOrUpdateStageMethod mergedMethod = new FluentDefinitionOrUpdateStageMethod(defMethod.Name, 
                                    defMethod.ParameterDeclaration, 
                                    defMethod.ParameterTypesKey);

                                string mergedBody = "if (isInCreateMode()) {" + "\n" + 
                                                   $"    {defMethod.Body}" + "\n" +
                                                    "} else {" + "\n" +
                                                   $"    {updateMethod.Body}" + "\n" +
                                                    "}";

                                mergedMethod.Body = mergedBody;
                                yield return mergedMethod;
                            }
                        }
                    }
                }
            }
        }
    }
}
